def _result_dtype_for_binary(lhs_dtype_obj: object, rhs_dtype_obj: object, op_obj: object) -> int: ...
def _result_dtype_for_reduction(dtype_obj: object, op_obj: object) -> int: ...
def _result_dtype_for_unary(dtype_obj: object) -> int: ...
def arange(start_obj: object, stop_obj: object, step_obj: object, dtype_obj: object) -> Array: ...
def asarray_from_buffer(obj: object, requested_dtype_obj: object, copy_obj: object) -> Array: ...
def astype(array_obj: object, dtype_obj: object) -> Array: ...
def binary(lhs_obj: object, rhs_obj: object, op_obj: object) -> Array: ...
def binary_into(dst_obj: object, lhs_obj: object, rhs_obj: object, op_obj: object) -> None: ...
def binary_scalar(array_obj: object, scalar_obj: object, scalar_dtype_obj: object, op_obj: object, scalar_on_left_obj: object) -> Array: ...
def broadcast_to(array_obj: object, shape_obj: object) -> Array: ...
def copy_from_external(data_address_obj: object, shape_obj: object, strides_obj: object, dtype_obj: object, byte_len_obj: object) -> Array: ...
def copyto(dst_obj: object, src_obj: object) -> None: ...
def diagonal(array_obj: object, offset_obj: object, axis1_obj: object, axis2_obj: object) -> Array: ...
def empty(shape_obj: object, dtype_obj: object) -> Array: ...
def fill(array_obj: object, value_obj: object) -> None: ...
def from_external(data_address_obj: object, shape_obj: object, strides_obj: object, dtype_obj: object, byte_len_obj: object) -> Array: ...
def from_flat(values_obj: object, shape_obj: object, dtype_obj: object) -> Array: ...
def full(shape_obj: object, value_obj: object, dtype_obj: object) -> Array: ...
def linalg_det(array_obj: object) -> Array: ...
def linalg_inv(array_obj: object) -> Array: ...
def linalg_solve(a_obj: object, b_obj: object) -> Array: ...
def linspace(start_obj: object, stop_obj: object, num_obj: object, dtype_obj: object) -> Array: ...
def materialize_c_contiguous(array_obj: object) -> Array: ...
def matmul(lhs_obj: object, rhs_obj: object) -> Array: ...
def reduce(array_obj: object, op_obj: object) -> Array: ...
def reshape(array_obj: object, shape_obj: object) -> Array: ...
def sin_add_mul(lhs_obj: object, rhs_obj: object, scalar_obj: object, scalar_dtype_obj: object) -> Array: ...
def slice(array_obj: object, starts_obj: object, stops_obj: object, steps_obj: object, drops_obj: object) -> Array: ...
def slice_1d(array_obj: object, start_obj: object, stop_obj: object, step_obj: object) -> Array: ...
def trace(array_obj: object, offset_obj: object, axis1_obj: object, axis2_obj: object, dtype_obj: object) -> Array: ...
def transpose(array_obj: object, axes_obj: object) -> Array: ...
def transpose_full_reverse(array_obj: object) -> Array: ...
def unary(array_obj: object, op_obj: object) -> Array: ...
def where(cond_obj: object, lhs_obj: object, rhs_obj: object) -> Array: ...

class Array:
  def add(self, other_obj: object) -> Array: ...
  def backend_code(self) -> int: ...
  def data_address(self) -> int: ...
  def div(self, other_obj: object) -> Array: ...
  def dtype_code(self) -> int: ...
  def get_scalar(self, index_obj: object) -> bool | int | float: ...
  def has_negative_strides(self) -> bool: ...
  def has_zero_strides(self) -> bool: ...
  def is_c_contiguous(self) -> bool: ...
  def is_f_contiguous(self) -> bool: ...
  def item_size(self) -> int: ...
  def matmul(self, other_obj: object) -> Array: ...
  def mul(self, other_obj: object) -> Array: ...
  def ndim(self) -> int: ...
  def shape_at(self, index_obj: object) -> int: ...
  def size(self) -> int: ...
  def slice_1d_method(self, start_obj: object, stop_obj: object, step_obj: object) -> Array: ...
  def storage_refcount(self) -> int: ...
  def stride_at(self, index_obj: object) -> int: ...
  def sub(self, other_obj: object) -> Array: ...
  def transpose_full_reverse_method(self) -> Array: ...
  def used_accelerate(self) -> bool: ...
  def used_fused(self) -> bool: ...
