from typing import Any

def arange(*args: Any, **kwargs: Any) -> Any: ...

def asarray_from_numpy(*args: Any, **kwargs: Any) -> Any: ...

def astype(*args: Any, **kwargs: Any) -> Any: ...

def binary(*args: Any, **kwargs: Any) -> Any: ...

def binary_into(*args: Any, **kwargs: Any) -> Any: ...

def binary_scalar(*args: Any, **kwargs: Any) -> Any: ...

def broadcast_to(*args: Any, **kwargs: Any) -> Any: ...

def copy_from_external(*args: Any, **kwargs: Any) -> Any: ...

def copyto(*args: Any, **kwargs: Any) -> Any: ...

def diagonal(*args: Any, **kwargs: Any) -> Any: ...

def empty(*args: Any, **kwargs: Any) -> Any: ...

def fill(*args: Any, **kwargs: Any) -> Any: ...

def from_external(*args: Any, **kwargs: Any) -> Any: ...

def from_flat(*args: Any, **kwargs: Any) -> Any: ...

def full(*args: Any, **kwargs: Any) -> Any: ...

def linalg_det(*args: Any, **kwargs: Any) -> Any: ...

def linalg_inv(*args: Any, **kwargs: Any) -> Any: ...

def linalg_solve(*args: Any, **kwargs: Any) -> Any: ...

def linspace(*args: Any, **kwargs: Any) -> Any: ...

def matmul(*args: Any, **kwargs: Any) -> Any: ...

def reduce(*args: Any, **kwargs: Any) -> Any: ...

def reshape(*args: Any, **kwargs: Any) -> Any: ...

def sin_add_mul(*args: Any, **kwargs: Any) -> Any: ...

def slice(*args: Any, **kwargs: Any) -> Any: ...

def slice_1d(*args: Any, **kwargs: Any) -> Any: ...

def trace(*args: Any, **kwargs: Any) -> Any: ...

def transpose(*args: Any, **kwargs: Any) -> Any: ...

def transpose_full_reverse(*args: Any, **kwargs: Any) -> Any: ...

def unary(*args: Any, **kwargs: Any) -> Any: ...

def where(*args: Any, **kwargs: Any) -> Any: ...

class Array:
  def add(self, *args: Any, **kwargs: Any) -> Any: ...
  def backend_code(self, *args: Any, **kwargs: Any) -> Any: ...
  def data_address(self, *args: Any, **kwargs: Any) -> Any: ...
  def div(self, *args: Any, **kwargs: Any) -> Any: ...
  def dtype_code(self, *args: Any, **kwargs: Any) -> Any: ...
  def get_scalar(self, *args: Any, **kwargs: Any) -> Any: ...
  def has_zero_strides(self, *args: Any, **kwargs: Any) -> Any: ...
  def is_c_contiguous(self, *args: Any, **kwargs: Any) -> Any: ...
  def is_f_contiguous(self, *args: Any, **kwargs: Any) -> Any: ...
  def item_size(self, *args: Any, **kwargs: Any) -> Any: ...
  def matmul(self, *args: Any, **kwargs: Any) -> Any: ...
  def mul(self, *args: Any, **kwargs: Any) -> Any: ...
  def ndim(self, *args: Any, **kwargs: Any) -> Any: ...
  def shape_at(self, *args: Any, **kwargs: Any) -> Any: ...
  def size(self, *args: Any, **kwargs: Any) -> Any: ...
  def slice_1d_method(self, *args: Any, **kwargs: Any) -> Any: ...
  def storage_refcount(self, *args: Any, **kwargs: Any) -> Any: ...
  def stride_at(self, *args: Any, **kwargs: Any) -> Any: ...
  def sub(self, *args: Any, **kwargs: Any) -> Any: ...
  def transpose_full_reverse_method(self, *args: Any, **kwargs: Any) -> Any: ...
  def used_accelerate(self, *args: Any, **kwargs: Any) -> Any: ...
  def used_fused(self, *args: Any, **kwargs: Any) -> Any: ...
